// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/wangle201210/ai-note/app/ai-note/internal/dao/internal"
)

// internalNoteDao is an internal type for wrapping the internal DAO implementation.
type internalNoteDao = *internal.NoteDao

// noteDao is the data access object for the table note.
// You can define custom methods on it to extend its functionality as needed.
type noteDao struct {
	internalNoteDao
}

var (
	// Note is a globally accessible object for table note operations.
	Note = noteDao{
		internal.NewNoteDao(),
	}
)

// Add your custom methods and functionality below.
