// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package note

import (
	"github.com/wangle201210/ai-note/app/ai-note/api/note"
)

type ControllerV1 struct{}

func NewV1() note.INoteV1 {
	return &ControllerV1{}
}
