// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package category

import (
	"github.com/wangle201210/ai-note/app/ai-note/api/category"
)

type ControllerV1 struct{}

func NewV1() category.ICategoryV1 {
	return &ControllerV1{}
}
